version: 2.1

workflows:
  main-wf:
    jobs:
      - para-metrics

jobs:
  para-metrics:
    docker:
      - image: cimg/base:2021.10
    steps:
      - run:
          name: "Install Para"
          command: |
            PARA_VER=0.5.0
            DL_URL="https://github.com/felicianotech/para/releases/download/v${PARA_VER}/para-v${PARA_VER}-linux-amd64.tar.gz"
            curl -sSL $DL_URL | sudo tar -xz -C /usr/local/bin para
      - run:
          name: "Orb Metrics"
          command: |
            echo "GoReleaser Orb:"
            para fetch --orb="hubci/goreleaser"
            echo "MD Proofer Orb:"
            para fetch --orb="hubci/md-proofer"
            echo "Sonar Orb:"
            para fetch --orb="hubci/sonar"
            echo "Gotham Orb:"
            para fetch --orb="hubci/gotham"
            echo "Strawberry Orb:"
            para fetch --orb="hubci/strawberry"
      - run:
          name: "Sonar Metrics"
          command: |
            para fetch --github="felicianotech/sonar" --brew="felicianotech/tap/sonar"
      - run:
          name: "cu-ddns Metrics"
          command: |
            para fetch --github="cloud-unpacked/cu-ddns"
      - run:
          name: "arc Metrics"
          command: |
            para fetch --github="hubci/arc" --brew="hubci/tap/sonar"
      - run:
          name: "Zoom MGR Metrics"
          command: |
            para fetch --github="felicianotech/zoom-mgr"
      - run:
          name: "Minecraft MGR Metrics"
          command: |
            para fetch --github="felicianotech/minecraft-mgr"
